# Site settings
title: Heiru Wu
description: TODO
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Heiru Wu
user_description: Hi, I'm a new grad student in Software Engineering.
#":" <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: Software Engineer Student
email: heiru52310.usc@gmail.com
twitter_username: HeiruWu
github_username:  gt212345
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
